server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/gamesphere
    username: postgres
    password: Prakash123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000 # 1 day in milliseconds
