spring:
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.gamesphere: DEBUG
